### ISSUE TITLE
[BUG] - .dddpcpatch not listed as valid Mod Archive type

### ISSUE THREAD

**Issue by SuperfieldCU** [OpenKH/OpenKh#988] opened 2024-02-05 07:08 UTC
**OpenKH Build**
963

**OpenKH Program**
Mod Manager

**Describe the Bug**
DDD support has at last been added, but the file select dialog to choose a mod archive or Lua script to install does not allow for .dddpcpatch files - it still only allows .zip, .kh2pcpatch, .kh1pcpatch, .compcpatch, .bbspcpatch and .lua files.

**To Reproduce**
1. Open Mod Manager.
2. Switch to Dream Drop Distance mode.
3. Click green plus to add mod.
4. Click "Select and install Mod Archive or Lua Script"
5. Navigate to folder containing .dddpcpatch files
6. .dddpcpatch files do not show up.

**Expected behavior**
.dddpcpatch files are visible and can be selected within the file dialog.

**Screenshots**
![image](https://github.com/OpenKH/OpenKh/assets/23531634/30b0102e-188d-4b19-a0bb-769a13f10685)

**Comment by shananas** [comment] 2024-02-05 17:47
technically not a bug as i forgot to add support for it.
just PRd support in #989

**Comment by shananas** [comment] 2024-02-06 02:02
with #989 merged now has support for dddpcpatch

**Closed by shananas** 2024-02-06 02:02 UTC
