### ISSUE TITLE
[Feature Request] Linux Port

### ISSUE THREAD

**Issue by Pixal-Aqua** [OpenKH/OpenKh#545] opened 2022-01-28 23:09 UTC
Hey, I don't know if you can but could you try to make a port of OpenKH to Linux, because on Linux you can run openkh.modsmanager.exe but not put in the path to it because it's not a valid path.

**Comment by Delta-473** [comment] 2022-01-29 00:22
Hey, all the command line applications do run natively on Linux, the gui apps need to use wine because the gui framework used at the moment is WPF. To get them running natively on Linux it needs to be ported to MAUI which is quite a bit of work. The mod manager itself is even more complicated as it uses Windows specific functions to hook into memory and do the patching. However someone on the discord did made a basic version of it for Linux.

**Comment by Pixal-Aqua** [comment] 2022-01-29 01:03
Where would I this basic version of it like channel wise.

**Comment by TauAkiou** [comment] 2023-03-26 20:44
openkh.modmanager.exe will work, provided that you run it in WINE, with the .NET6 Desktop package installed and the `HKEY_CURRENT_USER/Software/Microsoft/Avalon.Graphics/DisableHWAcceleration` DWORD key set to 1.

The best shot right now seems to be running it through Lutris using the regular Epic Launcher, in which the mod manager WILL run.

The hangup appears to currently be Panacea, which is currently attempting to call MakeSureDirectoryPathExists from imghelp.dll. My guess is that WINE does not call this function properly - in fact, WINE doesn't seem to like it much when DBGHELP.dll is overridden.

Would it be possible to build a version of Panacea that injects through an alternative DLL, such as version.dll instead? That might have a better chance of guaranteeing Linux compatibility (and is also the injection path used by other modloaders, which seems to offer better compatability overall).

**Comment by Kurumi78** [comment] 2023-07-16 04:30
Everything seems to work from my testing on Linux with #788 being merged. Seems to be the issue could be closed unless there is another tool not working right.

**Comment by TauAkiou** [comment] 2023-07-16 13:14
I would argue that there is much more work that needs to be done. Panacea support is the first step, but there are a huge number of features and programs that don't work natively, which I believe is the target for proper Linux support.

**Comment by Vladabdf** [comment] 2023-08-04 01:50
I have heard all of the GUI programs work under WINE, including the Mod Manager now. Is that not the case? I already confirmed myself all CLI tools work properly eons ago, so I assume that is still the case.

**Closed** 2024-06-18 14:26 UTC
Labels: Enhancement
