### ISSUE TITLE
[BUG] - Crash in Gummi Ship Missions running Panacea on Kingdom Hearts 2

### ISSUE THREAD

**Issue by cannon9009** [OpenKH/OpenKh#813] opened 2023-06-17 00:26 UTC
**OpenKH Build**
23.06.15.0

**OpenKH Program**
Panacea running Kingdom Hearts 2

**Describe the Bug**
Instead of starting Gummi Ship Missions, Kingdom Hearts 2 will hard crash to desktop when attempting to start the mission after the ship takes off while Panacea is installed.

**To Reproduce**
1. Start Kingdom Hearts II
2. Enter any Gummi Ship Mission
3. Select your ship and start the mission

**Expected behavior**
Mission should begin after starting, past the cutscene of your ship taking off

**Comment by Rox4sVentus** [comment] 2023-07-01 18:14
Same Issue,

KINGDOM HEARTS HD 1.5 + 2.5 ReMIX 
Epic version 1.0.0.8_WW

OpenKH Build
23.06.27.0

OpenKH Program
Panacea running Kingdom Hearts 2

Describe the Bug
Game crashes after the gummi launch scene just before starting both paths of the first time enter a gummi ship level, cant progress anymore in the game while Panacea is installed.

To Reproduce
Steps to reproduce the behavior:

1. Enter any Gummi Ship Mission
2. Enter any Gummi Ship Mission
3.Select your ship and start the mission

Expected behavior
Mission should begin after starting, past the cutscene of your ship taking off

**Comment by CodedRubyChan** [comment] 2023-07-01 19:47
The issue is known, sadly there hasn't been a fix yet. 
idk if there will be

**Comment by Yeet11212** [comment] 2023-08-05 05:27
Damn, this *literally* makes the game unplayable, at least when you want to go to any world past Hollow Bastion

**Comment by Vladabdf** [comment] 2023-09-08 13:50
Fixed as of #861

**Closed by Vladabdf** 2023-09-08 13:50 UTC
Labels: Bug, Help Wanted, 2/FM
