### ISSUE TITLE
[BUG] - Does not work with Steam version

### ISSUE THREAD

**Issue by qawasx** [OpenKH/OpenKh#1056] opened 2024-06-13 20:31 UTC
**OpenKH Build**
1104

**OpenKH Program**
OpenKh.Tools.ModsManager

**Describe the Bug**
The Mod Manager does not recognize Steam Folder Paths to the game exe as valid.

**To Reproduce**
1. Open OpenKh.Tools.ModsManager.exe
2. Click on game engine
3. Scroll down to PC release via Epic
4. entering steam Folder Location does not let me click next

**Expected behavior**
It should let me click next

**Screenshots**
![image](https://github.com/OpenKH/OpenKh/assets/110738181/abc99f22-3ab8-4797-9fc7-b659802c20fe)

**Comment by shananas** [comment] 2024-06-13 22:46
This is because the file this step of the setup wizard looks for is a dll that only comes with the EGS version of the game.
I am aware and will fix it but expect it to take time. I will not make a PR for 1 fix at a time so i need to rewrite sections of mod manager and test it for full compatiblity with both EGS and Steam release (not including Panacea/Mod Loader or LuaBackend These will need to be worked on by their devs).

Any bugs releated to Steam version will be expected for at least a month or more unless someone else finds time to fix it.

**Comment by qawasx** [comment] 2024-06-13 23:43
Thanks for your reply. Take your time with this and thanks for providing this mod for us. The KH ReFined also must be updated probably.

**Comment by Vladabdf** [comment] 2024-06-16 23:51
Fixed as of #1058. Please try the next release and report back.

**Comment by SuperCrunchTime** [comment] 2024-06-17 02:28
This allows some pieces of OpenKH to work with the steam version. It can correctly find the steam install paths and it seems to be able extract at least kh2 files at the end. However, trying to install panacea gives an invalid path error. Also, when I try to install a mod ([A bunch of keyblades](https://www.nexusmods.com/kingdomhearts2finalmix/mods/129?tab=description)), using the build and patch command, I get an index out of bounds error (Though, I don't know if this is caused by OpenKH or the mod itself).

**Comment by ChaosEternalRE** [comment] 2024-06-17 03:10
Looks like PcReleaseLocation is never being set which is causing the Panacea install error. I'll be looking into that.

**Comment by ChaosEternalRE** [comment] 2024-06-17 03:21
Ah, PCReleaseLocation is specific to the EGS release atm. A jank hardcoded fix would be easy, but something more elegant should be doable without much trouble. Perhaps create a new variable for the EGS stuff and have PCReleaseLocation point to either it or Steam depending on the circumstances. Or even both at the same time. Just need to think about how to best structure things.

**Comment by shananas** [comment] 2024-06-17 04:00
That is similar to what I plan on doing when I can get to it.

**Comment by Vladabdf** [comment] 2024-06-18 04:06
Should be fixed fully as of #1063. Please try [release 1120](https://github.com/OpenKH/OpenKh/releases/tag/release2-1120) and report back.

**Comment by TheSoraHD** [comment] 2024-06-18 11:14
Seems to be fully working here! Thanks for your hard work!!! =)

![GQVgVRsXwAAwj-Z](https://github.com/OpenKH/OpenKh/assets/8531824/168fd0b7-46f7-4821-be6e-c7eb08ffa230)
![GQVg1yhWIAAzUBa](https://github.com/OpenKH/OpenKh/assets/8531824/6d146b0b-d910-4506-85e5-2bc3f2f05d1a)
![GQVg74HXsAAeLWV](https://github.com/OpenKH/OpenKh/assets/8531824/6b6a33ed-0c5b-4433-a203-70cee311fbd9)

**Comment by qawasx** [comment] 2024-06-18 13:26
Thanks for your quick work!

**Closed** 2024-06-18 14:17 UTC
